ORDER_STATUS_PENDING = "pending"
ORDER_STATUS_CONFIRMED = "confirmed"
ORDER_STATUS_PREPARING = "preparing"
ORDER_STATUS_SHIPPED = "shipped"
ORDER_STATUS_DELIVERED = "delivered"
ORDER_STATUS_CANCELLED = "cancelled"
ORDER_STATUS_RETURN_REQUESTED = "return_requested"
ORDER_STATUS_RETURN_IN_TRANSIT = "return_in_transit"
ORDER_STATUS_RETURN_RECEIVED = "return_received"
ORDER_STATUS_RETURNED = "returned"

ORDER_STATUSES = {
    ORDER_STATUS_PENDING,
    ORDER_STATUS_CONFIRMED,
    ORDER_STATUS_PREPARING,
    ORDER_STATUS_SHIPPED,
    ORDER_STATUS_DELIVERED,
    ORDER_STATUS_CANCELLED,
    ORDER_STATUS_RETURN_REQUESTED,
    ORDER_STATUS_RETURN_IN_TRANSIT,
    ORDER_STATUS_RETURN_RECEIVED,
    ORDER_STATUS_RETURNED,
}

PAYMENT_STATUS_UNPAID = "unpaid"
PAYMENT_STATUS_PENDING = "pending"
PAYMENT_STATUS_PAID = "paid"
PAYMENT_STATUS_FAILED = "failed"
PAYMENT_STATUS_REFUNDED = "refunded"
PAYMENT_STATUS_PARTIALLY_REFUNDED = "partially_refunded"

PAYMENT_STATUSES = {
    PAYMENT_STATUS_UNPAID,
    PAYMENT_STATUS_PENDING,
    PAYMENT_STATUS_PAID,
    PAYMENT_STATUS_FAILED,
    PAYMENT_STATUS_REFUNDED,
    PAYMENT_STATUS_PARTIALLY_REFUNDED,
}

FULFILLMENT_STATUS_UNFULFILLED = "unfulfilled"
FULFILLMENT_STATUS_RESERVED = "reserved"
FULFILLMENT_STATUS_PROCESSING = "processing"
FULFILLMENT_STATUS_FULFILLED = "fulfilled"
FULFILLMENT_STATUS_RETURNING = "returning"
FULFILLMENT_STATUS_RETURNED = "returned"
FULFILLMENT_STATUS_CANCELLED = "cancelled"

FULFILLMENT_STATUSES = {
    FULFILLMENT_STATUS_UNFULFILLED,
    FULFILLMENT_STATUS_RESERVED,
    FULFILLMENT_STATUS_PROCESSING,
    FULFILLMENT_STATUS_FULFILLED,
    FULFILLMENT_STATUS_RETURNING,
    FULFILLMENT_STATUS_RETURNED,
    FULFILLMENT_STATUS_CANCELLED,
}

INVENTORY_MOVEMENT_INITIAL = "initial_stock"
INVENTORY_MOVEMENT_MANUAL = "manual_adjustment"
INVENTORY_MOVEMENT_RESERVATION = "reservation"
INVENTORY_MOVEMENT_RELEASE = "reservation_release"
INVENTORY_MOVEMENT_SALE = "sale"
INVENTORY_MOVEMENT_RETURN_RECEIVED = "return_received"
INVENTORY_MOVEMENT_RETURN_RESTOCKED = "return_restocked"
INVENTORY_MOVEMENT_RETURN_DAMAGED = "return_damaged"
INVENTORY_MOVEMENT_DAMAGE = "damage"
INVENTORY_MOVEMENT_LOSS = "loss"
INVENTORY_MOVEMENT_CORRECTION = "inventory_correction"

OUTBOX_PENDING = "pending"
OUTBOX_PROCESSING = "processing"
OUTBOX_SENT = "sent"
OUTBOX_FAILED = "failed"
OUTBOX_DEAD_LETTER = "dead_letter"
